#!/usr/bin/env node

/**
 * Build Verification Script
 * 
 * This script verifies that the build process produces valid plugin files.
 * It checks for the existence and validity of required files.
 */

import { readFileSync, existsSync, statSync } from 'fs';
import { join } from 'path';

const REQUIRED_FILES = ['main.js', 'manifest.json'];
const OPTIONAL_FILES = ['styles.css'];

let hasErrors = false;

console.log('🔍 Verifying build artifacts...\n');

// Check required files
for (const file of REQUIRED_FILES) {
	if (!existsSync(file)) {
		console.error(`❌ ERROR: Required file '${file}' not found`);
		hasErrors = true;
		continue;
	}

	const stats = statSync(file);
	if (stats.size === 0) {
		console.error(`❌ ERROR: File '${file}' is empty`);
		hasErrors = true;
		continue;
	}

	console.log(`✅ ${file} (${(stats.size / 1024).toFixed(2)} KB)`);
}

// Check optional files
for (const file of OPTIONAL_FILES) {
	if (existsSync(file)) {
		const stats = statSync(file);
		console.log(`✅ ${file} (${(stats.size / 1024).toFixed(2)} KB) [optional]`);
	} else {
		console.log(`ℹ️  ${file} not found (optional)`);
	}
}

// Validate manifest.json
console.log('\n🔍 Validating manifest.json...\n');

try {
	const manifestContent = readFileSync('manifest.json', 'utf8');
	const manifest = JSON.parse(manifestContent);

	const requiredFields = ['id', 'name', 'version', 'minAppVersion', 'description'];
	for (const field of requiredFields) {
		if (!manifest[field]) {
			console.error(`❌ ERROR: manifest.json missing required field '${field}'`);
			hasErrors = true;
		} else {
			console.log(`✅ manifest.${field}: ${manifest[field]}`);
		}
	}
} catch (error) {
	console.error(`❌ ERROR: Failed to parse manifest.json: ${error.message}`);
	hasErrors = true;
}

// Validate main.js
console.log('\n🔍 Validating main.js...\n');

try {
	const mainContent = readFileSync('main.js', 'utf8');
	
	// Check for esbuild banner
	if (!mainContent.includes('THIS IS A GENERATED/BUNDLED FILE BY ESBUILD')) {
		console.warn('⚠️  WARNING: main.js missing esbuild banner');
	} else {
		console.log('✅ main.js contains esbuild banner');
	}

	// Check for basic plugin structure
	if (!mainContent.includes('Plugin')) {
		console.error('❌ ERROR: main.js does not appear to contain plugin code');
		hasErrors = true;
	} else {
		console.log('✅ main.js contains plugin code');
	}

	// Check file size is reasonable (should be at least 10KB for a real plugin)
	const stats = statSync('main.js');
	if (stats.size < 10000) {
		console.warn('⚠️  WARNING: main.js seems unusually small');
	} else {
		console.log('✅ main.js size is reasonable');
	}
} catch (error) {
	console.error(`❌ ERROR: Failed to validate main.js: ${error.message}`);
	hasErrors = true;
}

// Validate versions.json
console.log('\n🔍 Validating versions.json...\n');

try {
	const versionsContent = readFileSync('versions.json', 'utf8');
	const versions = JSON.parse(versionsContent);
	const manifestContent = readFileSync('manifest.json', 'utf8');
	const manifest = JSON.parse(manifestContent);

	if (!versions[manifest.version]) {
		console.error(`❌ ERROR: versions.json missing entry for current version ${manifest.version}`);
		hasErrors = true;
	} else {
		console.log(`✅ versions.json contains entry for version ${manifest.version}`);
		console.log(`   Minimum Obsidian version: ${versions[manifest.version]}`);
	}
} catch (error) {
	console.error(`❌ ERROR: Failed to validate versions.json: ${error.message}`);
	hasErrors = true;
}

// Summary
console.log('\n' + '='.repeat(50));
if (hasErrors) {
	console.error('\n❌ Build verification FAILED\n');
	process.exit(1);
} else {
	console.log('\n✅ Build verification PASSED\n');
	console.log('All required files are present and valid.');
	console.log('The plugin is ready for release.');
	process.exit(0);
}
